name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      shell: cmd
      run: |
        pyinstaller --noconfirm --onefile --console ^
          --add-data "static;static" ^
          --add-data "templates;templates" ^
          server.py

    - name: Prepare distribution files
      run: |
        mkdir dist\server
        copy .\third_party_licenses\* dist\server
        copy .\LICENSE dist\server
        copy .\README.md dist\server
        copy .\README_CHS.md dist\server
        copy .\dist\server.exe dist\server
        copy .\config.toml dist\server

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: midishow_downloader-${{ matrix.arch }}
        path: dist/server/